#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
cd ~/GitRepos/JSS_Scripts

export EDITOR="/usr/local/bin/mate -w"

alias scripts="cd ~/GitRepos/JSS_Scripts"
alias eas="cd ~/GitRepos/JSS_EAs"
alias configs="cd ~/GitRepos/configProfiles"
alias ckh="rm -rf ~/.ssh/known_hosts"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

